const themes=[['Nebula Violet','#8b5cf6','#a78bfa','rgba(22,18,38,.76)'],['Cyber Cyan','#22d3ee','#67e8f9','rgba(8,31,42,.78)'],['Solar Ember','#f97316','#fb923c','rgba(42,21,9,.78)'],['Mint Matrix','#34d399','#6ee7b7','rgba(8,38,28,.78)']];
const episodes=[['The Last Horizon','S02E07 · Signal Flare','2026-06-18','Netflix','#ef4444'],['Arcane Cities','S01E10 · Clockwork','2026-06-21','Prime Video','#8b5cf6'],['Moonlit Kitchen','S04E02 · Midnight Ramen','2026-06-24','Hulu','#22d3ee']];
const events=[['Team planning','2026-06-15','09:30','Work'],['Gym + groceries','2026-06-16','18:00','Personal'],['Pay rent reminder','2026-07-01','08:00','Bills']];
let layout=['month','episodes','agenda','quickAdd','themes','wallpaper'],dragging=null,compact=false,theme=themes[0];
const root=document.documentElement,dashboard=document.querySelector('#dashboard');
function applyTheme(t){theme=t;root.style.setProperty('--accent',t[1]);root.style.setProperty('--glow',t[2]);root.style.setProperty('--panel',t[3]);}
function card(id,html){return `<article class="card ${id}" draggable="true" data-id="${id}"><span class="handle">⋮⋮ Drag</span>${html}</article>`}
function month(){return `<h2>June 2026</h2><div class="weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<b>${d}</b>`).join('')}</div><div class="month-grid">${Array.from({length:35},(_,i)=>i+1).map(d=>{const date=`2026-06-${String(d).padStart(2,'0')}`,ep=episodes.find(e=>e[2]===date),ev=events.find(e=>e[1]===date);return `<div class="day ${d===14?'today':''}"><strong>${d}</strong>${!compact&&ep?`<span class="pill" style="background:${ep[4]}">${ep[0]}</span>`:''}${!compact&&ev?`<span class="dot">${ev[3]}</span>`:''}</div>`}).join('')}</div>`}
function episodeWidget(){return `<h2>Episode radar</h2>${episodes.sort((a,b)=>a[2].localeCompare(b[2])).map(e=>`<div class="episode"><span style="background:${e[4]}"></span><div><b>${e[0]}</b><p>${e[1]}</p></div><time>${new Date(e[2]).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time><em>${e[3]}</em></div>`).join('')}`}
function agenda(){const rows=[...events.map(e=>[e[0],`${e[2]} · ${e[3]}`,e[1]]),...episodes.map(e=>[e[0],`${e[1]} · ${e[3]}`,e[2]])].sort((a,b)=>a[2].localeCompare(b[2])).slice(0,6);return `<h2>Smart agenda</h2>${rows.map(r=>`<div class="agenda-row"><time>${r[2].slice(5)}</time><div><b>${r[0]}</b><p>${r[1]}</p></div></div>`).join('')}`}
function quickAdd(){return `<h2>Quick add</h2><p class="muted">Templates for show seasons, recurring events, bills, birthdays, watch parties, and release reminders.</p><div class="mock-form"><input value="Show / event name" readonly><input value="Release date + reminder" readonly><select><option>Episode tracker</option></select></div><button id="save-demo">Save demo items</button>`}
function themeStudio(){return `<h2>Theme studio</h2><div class="swatches">${themes.map((t,i)=>`<button aria-label="${t[0]}" data-theme="${i}" class="${t===theme?'active':''}" style="background:linear-gradient(135deg,${t[1]},${t[2]})"></button>`).join('')}</div><label class="toggle"><input id="compact" type="checkbox" ${compact?'checked':''}> Compact layout density</label><p class="muted">Widgets persist as independent modules ready for plugin settings, custom feeds, and drag/drop dashboards.</p>`}
function wallpaper(){return `<h2>Desktop background</h2><p class="muted">Designed for Windows EXE packaging. Use dynamic mode as a borderless always-on-bottom window, or export a static 4K snapshot for Wallpaper Engine / Windows background rotation.</p><div class="wallpaper-preview"><span>🖥️</span><span>Live wallpaper-ready dashboard</span></div>`}
const widgets={month,episodes:episodeWidget,agenda,quickAdd,themes:themeStudio,wallpaper};
function render(){dashboard.className=compact?'dashboard compact':'dashboard';dashboard.innerHTML=layout.map(id=>card(id,widgets[id]())).join('');bind();}
function bind(){document.querySelectorAll('.card').forEach(el=>{el.ondragstart=()=>dragging=el.dataset.id;el.ondragover=e=>{e.preventDefault();if(dragging&&dragging!==el.dataset.id){layout=layout.filter(x=>x!==dragging);layout.splice(layout.indexOf(el.dataset.id),0,dragging);render();}};el.ondragend=()=>dragging=null;});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{applyTheme(themes[b.dataset.theme]);render();});document.querySelector('#compact')?.addEventListener('change',e=>{compact=e.target.checked;render();});document.querySelector('#save-demo')?.addEventListener('click',addDemo);}
function addDemo(){const date=new Date(Date.now()+(episodes.length+2)*86400000).toISOString().slice(0,10);episodes.unshift(['New tracked show',`S01E0${episodes.length+1} · Premiere`,date,'Custom source',theme[1]]);events.unshift(['Coffee with Sam',date,'14:00','Social']);render();}
document.querySelector('#add-anything').onclick=addDemo;applyTheme(theme);render();
